// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	parking "git.garena.com/sea-labs-id/batch-04/shared-projects/go-parking-lot/parking"
	mock "github.com/stretchr/testify/mock"
)

// ParkStyle is an autogenerated mock type for the ParkStyle type
type ParkStyle struct {
	mock.Mock
}

// ImplementStyle provides a mock function with given fields: _a0
func (_m *ParkStyle) ImplementStyle(_a0 []*parking.Lot) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewParkStyle interface {
	mock.TestingT
	Cleanup(func())
}

// NewParkStyle creates a new instance of ParkStyle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewParkStyle(t mockConstructorTestingTNewParkStyle) *ParkStyle {
	mock := &ParkStyle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
