// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	parking "git.garena.com/sea-labs-id/batch-04/shared-projects/go-parking-lot/parking"
	mock "github.com/stretchr/testify/mock"
)

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// NotifyAvailable provides a mock function with given fields: lot
func (_m *Subscriber) NotifyAvailable(lot *parking.Lot) {
	_m.Called(lot)
}

// NotifyFull provides a mock function with given fields: lot
func (_m *Subscriber) NotifyFull(lot *parking.Lot) {
	_m.Called(lot)
}

type mockConstructorTestingTNewSubscriber interface {
	mock.TestingT
	Cleanup(func())
}

// NewSubscriber creates a new instance of Subscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSubscriber(t mockConstructorTestingTNewSubscriber) *Subscriber {
	mock := &Subscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
